services:
  - type: web
    name: credify
    runtime: image
    image:
      url: docker.io/udaycodespace/credify:latest
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: sqlite:////tmp/credify.db
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: STUDENT_PASSWORD
        sync: false
      - key: PORT
        value: 5000
